@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Logic LOGIC_COLOR_T1
participant ":FilterCommand" as FilterCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:AttributeMatchesPredicate" as Predicate MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
participant "<<class>>\nAutoCorrectionUtil" as Util MODEL_COLOR
end box

[-> FilterCommand : execute(m)
activate FilterCommand

FilterCommand -> Model : autocorrectAttributeName("Mayor")
activate Model

ref#white over Model, Util : Autocorrect the attribute name "Mayor"

FilterCommand <-- Model : ["Major"]
deactivate Model

FilterCommand -> Model : autocorrectAttributeValue("CS")
activate Model

FilterCommand <-- Model : ["CS"]
deactivate Model

create Predicate
FilterCommand -> Predicate : Predicate(Set.of(new Attribute("Major", "CS")))
activate Predicate

FilterCommand <-- Predicate : p
deactivate Predicate

FilterCommand -> Model : updateFilteredPersonList(p)
activate Model

Model <-- FilterCommand
deactivate Model

FilterCommand -> Util : getWarningForName("Mayor", ["Major"])
activate Util

FilterCommand <-- Util : Warning message about the autocorrection
deactivate Util

FilterCommand -> Util : getWarningForValue("CS", ["CS"])
activate Util

FilterCommand <-- Util : No warning message
deactivate Util

FilterCommand -> Model : getFilteredPersonList()
activate Model

FilterCommand <-- Model
deactivate Model

[<-- FilterCommand : Command result with warning messages
deactivate FilterCommand

@enduml
