@startuml
!include style.puml
skinparam ArrowFontStyle plain

mainframe **sd**  Get the comparator for alphabetical sort

box Logic LOGIC_COLOR_T1
participant "d:LexSortCommand" as LexSortCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "c:AttributeBasedPersonComparator" as AttributeBasedPersonComparator MODEL_COLOR
participant "v:ValueBasedAttributeComparator" as ValueBasedAttributeComparator MODEL_COLOR
end box

activate LexSortCommand
LexSortCommand -> LexSortCommand ++ : getComparator(true)

create ValueBasedAttributeComparator
LexSortCommand -> ValueBasedAttributeComparator : ValueBasedAttributeComparator(true)
activate ValueBasedAttributeComparator

ValueBasedAttributeComparator --> LexSortCommand
deactivate ValueBasedAttributeComparator

create AttributeBasedPersonComparator
LexSortCommand -> AttributeBasedPersonComparator: AttributeBasedPersonComparator("location", v)
activate AttributeBasedPersonComparator

AttributeBasedPersonComparator --> LexSortCommand
deactivate AttributeBasedPersonComparator

return c

@enduml
