@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Logic LOGIC_COLOR_T1
participant "d:LexSortCommand" as LexSortCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "<<class>>\nAutoCorrectionUtil" as Util MODEL_COLOR
end box

[-> LexSortCommand : execute(m)
activate LexSortCommand

LexSortCommand -> Model : autocorrectAttributeName("Locaton")
activate Model

ref#white over Model, Util : Autocorrect the attribute name "Locaton"

LexSortCommand <-- Model : ["location"]
deactivate Model

ref#white over LexSortCommand, Model : Get the comparator for alphabetical sort

LexSortCommand -> Model : sortFilteredPersonList(c)
activate Model

Model --> LexSortCommand
deactivate Model

LexSortCommand -> LexSortCommand ++ : getWarningMessages(m)

LexSortCommand -> Util : getWarningForName("locaton", ["location"])
activate Util

Util --> LexSortCommand
deactivate Util

LexSortCommand -> Model : numOfPersonsWithAttribute("location")
activate Model

Model --> LexSortCommand
deactivate Model

return message

create CommandResult
LexSortCommand -> CommandResult : CommandResult(message)
activate CommandResult

CommandResult --> LexSortCommand
deactivate CommandResult

[<--LexSortCommand : r
deactivate LexSortCommand
@enduml
