@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":LexSortCommandParser" as LexSortCommandParser LOGIC_COLOR
participant "d:LexSortCommand" as LexSortCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant "c:AttributeBasedPersonComparator" as AttributeBasedPersonComparator LOGIC_COLOR
participant "v:ValueBasedAttributeComparator" as ValueBasedAttributeComparator LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort a/Location")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sort a/Location")
activate AddressBookParser

create LexSortCommandParser
AddressBookParser -> LexSortCommandParser
activate LexSortCommandParser

LexSortCommandParser --> AddressBookParser
deactivate LexSortCommandParser

AddressBookParser -> LexSortCommandParser : parse("a/Location")
activate LexSortCommandParser

create LexSortCommand
LexSortCommandParser -> LexSortCommand
activate LexSortCommand

LexSortCommand --> LexSortCommandParser :
deactivate LexSortCommand

LexSortCommandParser --> AddressBookParser : d
deactivate LexSortCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
LexSortCommandParser -[hidden]-> AddressBookParser
destroy LexSortCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> LexSortCommand : execute(m)
activate LexSortCommand

create ValueBasedAttributeComparator
LexSortCommand -> ValueBasedAttributeComparator
activate ValueBasedAttributeComparator

ValueBasedAttributeComparator --> LexSortCommand : v
deactivate ValueBasedAttributeComparator

create AttributeBasedPersonComparator
LexSortCommand -> AttributeBasedPersonComparator: AttributeBasedPersonComparator("Location", v)
activate AttributeBasedPersonComparator

AttributeBasedPersonComparator --> LexSortCommand: c
deactivate AttributeBasedPersonComparator

LexSortCommand -> Model : sortFilteredPersonList(c)
activate Model

Model --> LexSortCommand
deactivate Model

create CommandResult
LexSortCommand -> CommandResult
activate CommandResult

CommandResult --> LexSortCommand
deactivate CommandResult

LexSortCommand --> LogicManager : r
deactivate LexSortCommand

[<--LogicManager
deactivate LogicManager
@enduml
