@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "UndoCommand" as UC LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "Model" as Model MODEL_COLOR
participant "Stack<AddressBook>" as Stack MODEL_COLOR
participant "AddressBook" as AB MODEL_COLOR
end box

activate UC
[-> UC : execute

UC -> Model: revertLastState()
activate Model
loop while there are previous states and the last state is equal to the current state
    Model -> Stack: pop()
end loop
    alt model has no previous states
        break
        Model -> UC: throw IllegalStateException
        [<--UC: failure message
        end break
    end alt
    Model -> Stack: pop()
    activate Stack
        return last state
    deactivate Stack
    Model -> AB: resetData(last state)
    Model --> UC: associated command text of last change
deactivate Model

[<--UC : command result
deactivate UC

@enduml